services:
  nuxt:
    build: 
      context: .
      dockerfile: docker/nuxt/Dockerfile
    container_name: nuxt
    env_file:
      - .env
    volumes:
      - ./front:/app:cached 
      - nuxt_node_modules:/app/node_modules 
    ports: 
      - "80:3000"
      - "24678:24678"
    tty: true 
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: true
      NUXT_UPLOADTHING_TOKEN: ${NUXT_UPLOADTHING_TOKEN}
    command: sh -c "npm install && npm run dev"

  fast_api:
    build:
      context: .
      dockerfile: docker/fastAPI/Dockerfile 
    container_name: fast_api
    env_file:
      - .env
    ports:
        - "8000:8000"
    volumes: 
        - ./backend/app:/app:cached
        

volumes:
  nuxt_node_modules:
